# fly.toml app configuration file generated for jared-homepage-origin on 2023-06-06T12:15:41-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jared-homepage-origin"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "20s"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
